name: Build and release

on:
  # Dev
  workflow_dispatch:
  pull_request:
  push:
    # Preview
    branches: [ main ]
    # Stable
    tags: [ "v*" ]
  # Allow external PR with secrets
  pull_request_target:
    types: [labeled]

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yml
    with:
      dotnet_version: '8.0.100'
    secrets:
      test_resources: ${{ secrets.TEST_RESOURCES_URI_V1 }}
    # Allow to run in external PR if the label is present
    if: contains(github.event.pull_request.labels.*.name, 'allow workflow')

  # Preview release on push to main only
  # Stable release on version tag push only
  deploy:
    name: "Deploy"
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      dotnet_version: '8.0.100'
      azure_nuget_feed: 'https://pkgs.dev.azure.com/SceneGate/SceneGate/_packaging/SceneGate-Preview/nuget/v3/index.json'
    secrets:
      nuget_preview_token: "az" # Dummy values as we use Azure DevOps onlyg
      nuget_stable_token: "${{ secrets.NUGET_FEED_TOKEN }}"
      azure_nuget_token: ${{ secrets.ADO_NUGET_FEED_TOKEN }}
